import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import RedesSociais from '@/components/RedesSociais'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: '3D Motion',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt">
      <body className={inter.className}>
        <RedesSociais />
        {children}
      </body>
    </html>
  )
}
